#!/bin/sh
#

. /lib/partman/lib/base.sh

# Jose/Metztli IT 05-25-2025 moved logging below directive above as it
# now produces relevant output.
#
log() {
	logger -t partman-reiser4 "$@"
}
info() {
        log "info: $*"
}
#
# Jose/Metztli IT 05-20-2025 next two lines relevant for dialog
# querying user about reiser4 transparent compression Zstd formatting option.
set -e
. /usr/share/debconf/confmodule 

enable_swap

for dev in $DEVICES/*; do
	[ -d "$dev" ] || continue
	cd $dev
	partitions=
	open_dialog PARTITIONS
	while { read_line num id size type fs path name; [ "$id" ]; }; do
		[ "$fs" != free ] || continue
		partitions="$partitions $id,$num"
	done
	close_dialog

	for part in $partitions; do
		id=${part%,*}
		num=${part#*,}
		[ -f $id/method -a -f $id/format \
		  -a -f $id/acting_filesystem ] || continue
		filesystem=$(cat $id/acting_filesystem)
		case $filesystem in
		    reiser4)
			if [ -f $id/formatted ] && \
			   [ $id/formatted -nt $id/method ] && \
			   ([ ! -f $id/filesystem ] || \
			    [ $id/formatted -nt $id/filesystem ]); then
				continue
			fi
			log "Try to create file system for $dev/$id"
			if [ -f $id/mountpoint ]; then
				template=partman-basicfilesystems/progress_formatting_mountable
				db_subst $template MOUNT_POINT "$(cat $id/mountpoint)"
			else
				template=partman-basicfilesystems/progress_formatting
			fi
			open_dialog PARTITION_INFO $id
			read_line x1 x2 x3 x4 x5 device x6
			close_dialog

			RET=''
			db_metaget  partman/filesystem_short/"$filesystem" description || RET=''
			[ "$RET" ] || RET="$filesystem"
			db_subst $template TYPE "$RET"
			db_subst $template PARTITION "$num"
			db_subst $template DEVICE $(humandev $(cat device))

			db_progress START 0 3 partman/text/formatting
			db_progress INFO $template
			db_progress SET 1

			# Jose/Metztli IT 05-20-2025
			# Use transparent compression Zstd?
			# Ask user...
			db_input low partman-reiser4/reiser4_transparent_compression_zstd || true
			db_go || true

			if db_get partman-reiser4/reiser4_transparent_compression_zstd && [ "$RET" ]; then
				info "Inayamo RET is: $RET inside format_reiser4"
				[[ "$RET" == "Y" ]]
				info "Zatlatzaccan RET is: $RET inside format_reiser4"
				log-output -t partman --pass-stdout \
				mkfs.reiser4 -yo "compress=zstd1" $device >/dev/null
			else
				log-output -t partman --pass-stdout \
				# Jose/Metztli IT 03-06-2020 Software Framework Release Number (SFRN) 5.x.y scale out explicit default
				# mkfs.reiser4 -yo "create=reg42" $device >/dev/null
				# Jose/Metztli IT 08-21-2024 Software Framework Release Number (SFRN) 4.x.y 
				mkfs.reiser4 -yo "create=reg40" $device >/dev/null
			fi
				   		 
			code=$?
			sync
			db_progress STOP

			if [ "$code" = 0 ]; then
				label=''
				if [ -f $id/label ]; then
					label=$(cat $id/label | \
						sed 's/\(................\).*/\1/g')
				fi
			fi

			if [ "$code" != 0 ]; then
				T=partman-basicfilesystems/create_failed
				db_subst $T TYPE reiser4
				db_subst $T PARTITION "$num"
				db_subst $T DEVICE $(humandev $(cat device))
				db_input critical $T || true
				db_go || true
				#disable_swap
				exit 1
			fi
			>$id/formatted
			;;
		esac
	done
done

#disable_swap
