#!/bin/sh

dev=$1
id=$2
property=$3

[ -f /var/lib/partman/reiser4 ] || exit 0

case $property in
    formatable)
	echo reiser4
	;;
    existing)
	[ -f $id/detected_filesystem ] || exit 0
	fs=$(cat $id/detected_filesystem)

	case "$fs" in
	    reiser4)
		echo reiser4
		;;
	esac
	;;
esac


