#!/bin/sh
# yaboot does not work with /boot on reiser4. Detect and warn.
if [ "`udpkg --print-architecture`" != powerpc ]; then
	exit 0
fi

. /lib/partman/lib/base.sh

get_reiser4_root_boot () {
	(for i in /lib/partman/fstab.d/*; do
		[ -x "$i" ] || continue
		$i
	done) |
	while read fs mp type options dump pass; do
		if [ "$mp" = / ]; then
			echo root_type=$type
		elif [ "$mp" = /boot ]; then
			echo boot_type=$type
		fi
	done
}
eval "$(get_reiser4_root_boot)"

if [ "$boot_type" = reiser4 ]; then
	db_input critical partman-reiser4/reiser4_boot || true
	db_go || exit 1
	db_get partman-reiser4/reiser4_boot
	if [ "$RET" = false ]; then
		exit 1
	fi
fi

if [ "$boot_type" = "" ] && [ "$root_type" = reiser4 ]; then
	db_input critical partman-reiser4/reiser4_root || true
	db_go || exit 1
	db_get partman-reiser4/reiser4_root
	if [ "$RET" = false ]; then
		exit 1
	fi
fi
